"""add day to cours

Revision ID: 52a8ab26dca4
Revises: c706877a3f32
Create Date: 2025-01-30 22:29:29.765278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52a8ab26dca4'
down_revision = 'c706877a3f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jour', sa.String(length=50), nullable=True))
        batch_op.drop_column('devoir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devoir', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('jour')

    # ### end Alembic commands ###
