"""add day to cours

Revision ID: 886dafb43d71
Revises: 52a8ab26dca4
Create Date: 2025-01-30 22:47:37.021695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '886dafb43d71'
down_revision = '52a8ab26dca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('devoir', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('cours_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classe', ['classe_id'], ['id'])
        batch_op.drop_column('user_concerner')

    with op.batch_alter_table('devoir', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('devoir_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classe', ['classe_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devoir', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('devoir_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('classe_id')

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_concerner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cours_ibfk_2', 'user', ['user_concerner'], ['id'])
        batch_op.drop_column('devoir')
        batch_op.drop_column('classe_id')

    # ### end Alembic commands ###
