"""Update relationships between User, Cours, Devoir, and Classe

Revision ID: a5eadca19f87
Revises: 886dafb43d71
Create Date: 2025-02-04 14:32:14.801508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eadca19f87'
down_revision = '886dafb43d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matiere',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matiere')
    # ### end Alembic commands ###
