"""Update relationships between User, Cours, Devoir, and Classe

Revision ID: c1727d28d365
Revises: a5eadca19f87
Create Date: 2025-02-04 17:29:45.305813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1727d28d365'
down_revision = 'a5eadca19f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('prenom',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('mail',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=1500),
               existing_nullable=False)
        batch_op.alter_column('mdp',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=2550),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mdp',
               existing_type=sa.String(length=2550),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('mail',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('prenom',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
