name: CI Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les outils nécessaires
        run: |
          pip install flake8 pytest coverage

      - name: Linting avec Flake8
        run: flake8 --max-line-length=550 --exclude=venv,migrations
        continue-on-error: true
      - name: Exécution des tests

  sonarqube:
    name: SONAR_TOKEN
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: sqp_3daafdbb902755c1d3a7f48209f4c6d4a36ca149
        SONAR_HOST_URL: http://127.0.0.1:9000/
