name: CI Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les outils nécessaires
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip default-jre
          pip install flake8 pytest coverage

      - name: Lancer MySQL en local
        run: |
          docker run -d --name mysql-container -p 3306:3306 \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=testdb \
            -e MYSQL_USER=user \
            -e MYSQL_PASSWORD=password \
            mysql:8.0

      - name: Linting avec Flake8
        run: flake8 --max-line-length=120 --exclude=venv,migrations

      - name: Exécution des tests
        env:
          DATABASE_URL: "mysql://user:password@localhost:3306/testdb"
        run: pytest tests/
