name: CI Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les outils nécessaires
        run: |
          pip install flake8 pytest coverage

      - name: Linting avec Flake8
        run: flake8 --max-line-length=550 --exclude=venv,migrations
        continue-on-error: true
      - name: Exécution des tests
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/ENT"
        run: pytest .
